//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VehicleSetup3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Complience
    {
        public int ID { get; set; }
        public string FleetNo { get; set; }
        public int ComplienceTypeID { get; set; }
        public int SubTypeID { get; set; }
        public string LicenceClass { get; set; }
        public string LicenseNo { get; set; }
        public Nullable<System.DateTime> DateObtained { get; set; }
        public Nullable<System.DateTime> ValidFromDate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public string AlertOperation { get; set; }
    
        public virtual ComplienceSubType ComplienceSubType { get; set; }
        public virtual ComplienceType ComplienceType { get; set; }
        public virtual FleetAsset FleetAsset { get; set; }
    }
}
